apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "kafka.name" . }}
    chart: {{ template "kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.port }}
      name: broker
  selector:
    app: {{ template "kafka.name" . }}
    release: {{ .Release.Name }}
