apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  labels:
    app: kafka-connect
    release: {{ .Release.Name }}
spec:
  ports:
    - name: kafka-connect
      port: {{ .Values.servicePort }}
  selector:
    app: kafka-connect
    release: {{ .Release.Name }}
